baseURL = "https://midesweb.github.io/mi-sitio/"
languageCode = "es"
title = "InmoCasas"
theme = "tale"

[Author]
  name = "Miguel Angel Alvarez"

[menu]
  [[menu.main]]
    identifier = "contacto"
    name = "Contacto"
    title = "Contacto"
    url = "/contacto/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0

[params]
  css = ["css/estilos.css"]